import { GitHubClient } from './github_client';
import { ReviewResult, ReviewIssue } from './reviewer';

export class Commenter {
  private githubClient: GitHubClient;

  constructor(githubClient: GitHubClient) {
    this.githubClient = githubClient;
  }

  async postReview(prNumber: number, review: ReviewResult): Promise<void> {
    const body = this.formatReviewComment(review);
    await this.githubClient.createReviewComment(prNumber, body);
  }

  private formatReviewComment(review: ReviewResult): string {
    const sections: string[] = [];

    // 标题
    sections.push('## 🤖 Claude Code Review\n');

    // 摘要
    sections.push(`### Summary\n${review.summary}\n`);

    // 问题列表
    if (review.issues.length > 0) {
      sections.push('### Issues Found\n');
      for (const issue of review.issues) {
        const emoji = this.getSeverityEmoji(issue.severity);
        sections.push(`${emoji} **${issue.file}${issue.line ? `:${issue.line}` : ''}**`);
        sections.push(`- ${issue.description}`);
        sections.push(`- Suggestion: ${issue.suggestion}\n`);
      }
    } else {
      sections.push('### ✅ No Issues Found\n');
    }

    // 建议
    if (review.suggestions.length > 0) {
      sections.push('### Suggestions\n');
      for (const suggestion of review.suggestions) {
        sections.push(`- ${suggestion}`);
      }
    }

    sections.push('\n---\n*This review was automatically generated by Claude Code*');

    return sections.join('\n');
  }

  private getSeverityEmoji(severity: string): string {
    switch (severity) {
      case 'high': return '🔴';
      case 'medium': return '🟡';
      case 'low': return '🟢';
      default: return '⚪';
    }
  }
}
